site_name: TDB Internal Documentation
nav:
    - Home : index.md
    - Rules:
      - General: rules/general.md 
      - Filename/Directory: rules/filenames.md
      - Track Naming: rules/tracks.md
      - Releases: rules/releases.md


theme:
  name: material
  logo: assets/torrentdb-logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.indexes

    - navigation.tracking
    - navigation.tabs
    - offline
  palette:
    - media: "(prefers-color-scheme: light)" 


      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 


      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


version: 11.0
navigation_depth: 3
nav_style:
  name: TDB Internal Documentation
  nav_style: dark
markdown_extensions:
    - tables
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
        permalink: True
    - attr_list
    - md_in_html
extra:
    version: Version 1.0
extra_css:
  - stylesheets/extra.css